# Generated by Django 2.2.16 on 2020-09-13 09:58

from django.db import migrations, models
import django.db.models.deletion
import procurement_portal.records.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('provenance', models.TextField()),
                ('online_source_url', models.URLField(blank=True, max_length=300, null=True)),
                ('trusted_archive_url', models.URLField(blank=True, max_length=300, null=True)),
                ('enabled', models.BooleanField(default=True)),
            ],
            bases=(models.Model, procurement_portal.records.models.UpdateTimestampsMixin),
        ),
        migrations.CreateModel(
            name='DatasetVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('file', models.FileField(upload_to=procurement_portal.records.models.file_path)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='records.Dataset')),
            ],
            bases=(models.Model, procurement_portal.records.models.UpdateTimestampsMixin),
        ),
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField()),
            ],
            bases=(models.Model, procurement_portal.records.models.UpdateTimestampsMixin),
        ),
        migrations.CreateModel(
            name='PurchaseRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_name', models.CharField(max_length=500)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('dataset_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='records.DatasetVersion')),
            ],
            bases=(models.Model, procurement_portal.records.models.UpdateTimestampsMixin),
        ),
        migrations.AddField(
            model_name='dataset',
            name='current_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='records.DatasetVersion'),
        ),
        migrations.AddField(
            model_name='dataset',
            name='repository',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='records.Repository'),
        ),
    ]
