# Generated by Django 3.1.1 on 2020-09-28 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("records", "0008_auto_20200928_2111"),
    ]

    operations = [
        migrations.RenameField(
            model_name="purchaserecord",
            old_name="order_amount_value_zar",
            new_name="order_amount_zar",
        ),
    ]
