# Generated by Django 3.1.1 on 2020-09-28 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0010_auto_20200928_2118'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaserecord',
            name='bbbee_status',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
