# Generated by Django 3.1.1 on 2020-10-12 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0014_auto_20201012_0642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaserecord',
            name='bbbee_status',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='purchaserecord',
            name='central_supplier_database_number',
            field=models.CharField(blank=True, db_index=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='purchaserecord',
            name='company_registration_number',
            field=models.CharField(blank=True, db_index=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='purchaserecord',
            name='director_names',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='purchaserecord',
            name='director_names_and_surnames',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='purchaserecord',
            name='director_surnames',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='purchaserecord',
            name='disbursement_number',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='purchaserecord',
            name='implementation_location_district_municipality',
            field=models.CharField(blank=True, db_index=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='purchaserecord',
            name='implementation_location_facility',
            field=models.CharField(blank=True, db_index=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='purchaserecord',
            name='implementation_location_local_municipality',
            field=models.CharField(blank=True, db_index=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='purchaserecord',
            name='implementation_location_other',
            field=models.CharField(blank=True, db_index=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='purchaserecord',
            name='implementation_location_province',
            field=models.CharField(blank=True, db_index=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='purchaserecord',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='purchaserecord',
            name='items_description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='purchaserecord',
            name='items_quantity',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='purchaserecord',
            name='items_unit',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='purchaserecord',
            name='order_number',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='purchaserecord',
            name='payment_number',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='purchaserecord',
            name='payment_period',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='purchaserecord',
            name='procurement_method',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='purchaserecord',
            name='state_employee',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
