# Generated by Django 3.1.1 on 2020-11-08 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0018_add_supplier_numbers'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasetversion',
            name='import_report',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='datasetversion',
            name='imported',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='datasetversion',
            name='dataset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='records.dataset'),
        ),
    ]
