# Generated by Django 3.1.1 on 2020-11-08 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0019_auto_20201108_0729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasetversion',
            name='imported',
            field=models.BooleanField(default=False),
        ),
    ]
