# Generated by Django 3.1.1 on 2020-11-08 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0020_auto_20201108_0753'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datasetversion',
            options={'ordering': ['dataset__name', '-created']},
        ),
        migrations.RemoveField(
            model_name='dataset',
            name='enabled',
        ),
    ]
